/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#pragma once

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include <mpx-events/mpx-events.h>

enum MpxConsumerEventCode {
	MpxConsumerEventACode = 1,
	MpxConsumerEventBCode = 2,
};
typedef enum MpxConsumerEventCode MpxConsumerEventCode;

struct MpxConsumerEventAStruct {
	MpxEventBaseStruct base;
	char *m_string;
};
typedef struct MpxConsumerEventAStruct MpxConsumerEventAStruct;

struct MpxConsumerEventBStruct {
	MpxEventBaseStruct base;
	int alpha;
	int beta;
	int gama;
};
typedef struct MpxConsumerEventBStruct MpxConsumerEventBStruct;

struct MpxConsumerEventStruct {
	MpxConsumerEventCode m_code;
	union {
		MpxConsumerEventAStruct m_ConsumerEventA;
		MpxConsumerEventBStruct m_ConsumerEventB;
	} MpxConsumerEventStruct_u;
};
typedef struct MpxConsumerEventStruct MpxConsumerEventStruct;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_MpxConsumerEventCode (XDR *, MpxConsumerEventCode*);
extern  bool_t xdr_MpxConsumerEventAStruct (XDR *, MpxConsumerEventAStruct*);
extern  bool_t xdr_MpxConsumerEventBStruct (XDR *, MpxConsumerEventBStruct*);
extern  bool_t xdr_MpxConsumerEventStruct (XDR *, MpxConsumerEventStruct*);

#else /* K&R C */
extern bool_t xdr_MpxConsumerEventCode ();
extern bool_t xdr_MpxConsumerEventAStruct ();
extern bool_t xdr_MpxConsumerEventBStruct ();
extern bool_t xdr_MpxConsumerEventStruct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif
