/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MPX_MESSAGES_H_RPCGEN
#define _MPX_MESSAGES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


enum MpxMessageCode {
	Illegal = 0,
	ExternalTaskRequestCode = 1,
	ExternalTaskReplyCode = 2,
};
typedef enum MpxMessageCode MpxMessageCode;

struct MpxExternalTaskRequest {
	char *taskName;
};
typedef struct MpxExternalTaskRequest MpxExternalTaskRequest;

struct MpxExternalTaskReply {
	long task;
};
typedef struct MpxExternalTaskReply MpxExternalTaskReply;

struct MpxMessage {
	MpxMessageCode m_Code;
	union {
		MpxExternalTaskRequest m_externalTaskRequest;
		MpxExternalTaskReply m_externalTaskReply;
	} MpxMessage_u;
};
typedef struct MpxMessage MpxMessage;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_MpxMessageCode (XDR *, MpxMessageCode*);
extern  bool_t xdr_MpxExternalTaskRequest (XDR *, MpxExternalTaskRequest*);
extern  bool_t xdr_MpxExternalTaskReply (XDR *, MpxExternalTaskReply*);
extern  bool_t xdr_MpxMessage (XDR *, MpxMessage*);

#else /* K&R C */
extern bool_t xdr_MpxMessageCode ();
extern bool_t xdr_MpxExternalTaskRequest ();
extern bool_t xdr_MpxExternalTaskReply ();
extern bool_t xdr_MpxMessage ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MPX_MESSAGES_H_RPCGEN */
