/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mpx-tasks/mpx-messages.h"

bool_t
xdr_MpxMessageCode (XDR *xdrs, MpxMessageCode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MpxExternalTaskRequest (XDR *xdrs, MpxExternalTaskRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->taskName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->encdeclib, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MpxExternalTaskReply (XDR *xdrs, MpxExternalTaskReply *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->task))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->encdeclib, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MpxMessage (XDR *xdrs, MpxMessage *objp)
{
	register int32_t *buf;

	 if (!xdr_MpxMessageCode (xdrs, &objp->m_Code))
		 return FALSE;
	switch (objp->m_Code) {
	case ExternalTaskRequestCode:
		 if (!xdr_MpxExternalTaskRequest (xdrs, &objp->MpxMessage_u.m_externalTaskRequest))
			 return FALSE;
		break;
	case ExternalTaskReplyCode:
		 if (!xdr_MpxExternalTaskReply (xdrs, &objp->MpxMessage_u.m_externalTaskReply))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
