/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mpx-events/mpx-events.h"

bool_t
xdr_MpxEventCode (XDR *xdrs, MpxEventCode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_taskid_t (XDR *xdrs, taskid_t *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MpxEventBaseStruct (XDR *xdrs, MpxEventBaseStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->m_code))
		 return FALSE;
	 if (!xdr_taskid_t (xdrs, &objp->m_src))
		 return FALSE;
	 if (!xdr_taskid_t (xdrs, &objp->m_dst))
		 return FALSE;
	return TRUE;
}
