var annotated_dup =
[
    [ "mpx", "d8/d67/namespacempx.html", "d8/d67/namespacempx" ],
    [ "MpxConsumerEventStruct", "d8/d15/structMpxConsumerEventStruct.html", "d8/d15/structMpxConsumerEventStruct" ],
    [ "MpxEventBaseStruct", "db/d6b/structMpxEventBaseStruct.html", "db/d6b/structMpxEventBaseStruct" ],
    [ "MpxEventStruct", "df/dd1/structMpxEventStruct.html", "df/dd1/structMpxEventStruct" ],
    [ "MpxExternalTaskEventStruct", "dc/d52/structMpxExternalTaskEventStruct.html", "dc/d52/structMpxExternalTaskEventStruct" ],
    [ "MpxExternalTaskReply", "d8/d74/structMpxExternalTaskReply.html", "d8/d74/structMpxExternalTaskReply" ],
    [ "MpxExternalTaskRequest", "db/d9c/structMpxExternalTaskRequest.html", "db/d9c/structMpxExternalTaskRequest" ],
    [ "MpxJobFinishedEventStruct", "d2/d5f/structMpxJobFinishedEventStruct.html", "d2/d5f/structMpxJobFinishedEventStruct" ],
    [ "MpxLocalClientEventStruct", "dc/dc4/structMpxLocalClientEventStruct.html", "dc/dc4/structMpxLocalClientEventStruct" ],
    [ "MpxLocalEndPointEventStruct", "d4/d04/structMpxLocalEndPointEventStruct.html", "d4/d04/structMpxLocalEndPointEventStruct" ],
    [ "MpxLocalListenerEventStruct", "d1/d81/structMpxLocalListenerEventStruct.html", "d1/d81/structMpxLocalListenerEventStruct" ],
    [ "MpxLocalTaskQueryEventStruct", "d7/dd5/structMpxLocalTaskQueryEventStruct.html", "d7/dd5/structMpxLocalTaskQueryEventStruct" ],
    [ "MpxMessage", "d2/d5b/structMpxMessage.html", "d2/d5b/structMpxMessage" ],
    [ "MpxPosixMQEventStruct", "d0/d51/structMpxPosixMQEventStruct.html", "d0/d51/structMpxPosixMQEventStruct" ],
    [ "MpxPosixMQTaskQueryEventStruct", "db/d59/structMpxPosixMQTaskQueryEventStruct.html", "db/d59/structMpxPosixMQTaskQueryEventStruct" ],
    [ "MpxStartEventStruct", "dc/d40/structMpxStartEventStruct.html", "dc/d40/structMpxStartEventStruct" ],
    [ "MpxStopEventStruct", "de/d41/structMpxStopEventStruct.html", "de/d41/structMpxStopEventStruct" ],
    [ "MpxTaskQueryEventStruct", "d6/d8b/structMpxTaskQueryEventStruct.html", "d6/d8b/structMpxTaskQueryEventStruct" ],
    [ "MpxTaskResponseEventStruct", "de/d9a/structMpxTaskResponseEventStruct.html", "de/d9a/structMpxTaskResponseEventStruct" ],
    [ "MpxTcp4ClientEventStruct", "de/d84/structMpxTcp4ClientEventStruct.html", "de/d84/structMpxTcp4ClientEventStruct" ],
    [ "MpxTcp4EndPointEventStruct", "d5/dd1/structMpxTcp4EndPointEventStruct.html", "d5/dd1/structMpxTcp4EndPointEventStruct" ],
    [ "MpxTcp4ListenerEventStruct", "de/d0f/structMpxTcp4ListenerEventStruct.html", "de/d0f/structMpxTcp4ListenerEventStruct" ],
    [ "MpxTcp4TaskQueryEventStruct", "d3/dcd/structMpxTcp4TaskQueryEventStruct.html", "d3/dcd/structMpxTcp4TaskQueryEventStruct" ],
    [ "MpxTcp6ClientEventStruct", "d2/d85/structMpxTcp6ClientEventStruct.html", "d2/d85/structMpxTcp6ClientEventStruct" ],
    [ "MpxTcp6EndPointEventStruct", "de/dad/structMpxTcp6EndPointEventStruct.html", "de/dad/structMpxTcp6EndPointEventStruct" ],
    [ "MpxTcp6ListenerEventStruct", "d2/d42/structMpxTcp6ListenerEventStruct.html", "d2/d42/structMpxTcp6ListenerEventStruct" ],
    [ "MpxTcp6TaskQueryEventStruct", "d3/df0/structMpxTcp6TaskQueryEventStruct.html", "d3/df0/structMpxTcp6TaskQueryEventStruct" ],
    [ "MpxTimerEventStruct", "d6/d73/structMpxTimerEventStruct.html", "d6/d73/structMpxTimerEventStruct" ],
    [ "MpxUdp4TaskQueryEventStruct", "d5/d0f/structMpxUdp4TaskQueryEventStruct.html", "d5/d0f/structMpxUdp4TaskQueryEventStruct" ],
    [ "MpxUdp6TaskQueryEventStruct", "db/d74/structMpxUdp6TaskQueryEventStruct.html", "db/d74/structMpxUdp6TaskQueryEventStruct" ]
];