/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ftpmsg/ftpmsg.h"

void dump_FtpRequest (FtpRequest *req, char* msg)
{
 if (req == 0)
 return;
 printf ("REQUEST: (%s)\n", (msg == 0) ? "" : msg);
 FtpConnectionInfo *connection = &req->connection;
 char *hostname = connection->hostname;
 char *user = connection->user;
 char *password = connection->password;
 char *authentication = connection->authentication;
 int flags = connection->flags;
 if (hostname != 0)
 printf ("   hostname = %s\n", hostname);
 if (user != 0)
 printf ("   user = %s\n", user);
 if (password != 0)
 printf ("   password = %s\n", password);
 if (authentication != 0)
 printf ("   authentication = %s\n", authentication);
 if (flags & FTP_SSH_OPERATION)
 printf ("   protocol = ssh2\n");
 else
 printf ("   protocol = ftp\n");
}


bool_t
xdr_FtpRequestCode (XDR *xdrs, FtpRequestCode *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FtpExceptionAction (XDR *xdrs, FtpExceptionAction *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ExceptionFileList (XDR *xdrs, ExceptionFileList *objp)
{
	register int32_t *buf;

	 if (!xdr_FtpExceptionAction (xdrs, &objp->action))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (ExceptionFileList), (xdrproc_t) xdr_ExceptionFileList))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fileNameTemplate, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FtpConnectionInfo (XDR *xdrs, FtpConnectionInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->hostname, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->user, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->password, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->authentication, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flags))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CheckConnectivityRequest (XDR *xdrs, CheckConnectivityRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dummy))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MakeDirRequest (XDR *xdrs, MakeDirRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_GetDirRequest (XDR *xdrs, GetDirRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StoreFileRequest (XDR *xdrs, StoreFileRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->localDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->localFileName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->remoteFileName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->workingDirName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RetrieveFileRequest (XDR *xdrs, RetrieveFileRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->localDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->localFileName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->remoteFileName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->workingDirName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_StoreAllFilesRequest (XDR *xdrs, StoreAllFilesRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->localDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->workingDirName, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->exceptions, sizeof (ExceptionFileList), (xdrproc_t) xdr_ExceptionFileList))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RetrieveAllFilesRequest (XDR *xdrs, RetrieveAllFilesRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->localDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->workingDirName, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->exceptions, sizeof (ExceptionFileList), (xdrproc_t) xdr_ExceptionFileList))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DeleteFileRequest (XDR *xdrs, DeleteFileRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->remoteFileName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DeleteAllFilesRequest (XDR *xdrs, DeleteAllFilesRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->exceptions, sizeof (ExceptionFileList), (xdrproc_t) xdr_ExceptionFileList))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MakeWorkingEnvRequest (XDR *xdrs, MakeWorkingEnvRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->workingDirName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_CleanDirRequest (XDR *xdrs, CleanDirRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->remoteDirName, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_EmptyFtpRequest (XDR *xdrs, EmptyFtpRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->empty))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FtpRequestUnion (XDR *xdrs, FtpRequestUnion *objp)
{
	register int32_t *buf;

	 if (!xdr_FtpRequestCode (xdrs, &objp->requestCode))
		 return FALSE;
	switch (objp->requestCode) {
	case FirstRequest:
		 if (!xdr_EmptyFtpRequest (xdrs, &objp->FtpRequestUnion_u.empty))
			 return FALSE;
		break;
	case CheckConnectivity:
		 if (!xdr_CheckConnectivityRequest (xdrs, &objp->FtpRequestUnion_u.checkConnectivity))
			 return FALSE;
		break;
	case MakeDir:
		 if (!xdr_MakeDirRequest (xdrs, &objp->FtpRequestUnion_u.makeDir))
			 return FALSE;
		break;
	case GetDir:
		 if (!xdr_GetDirRequest (xdrs, &objp->FtpRequestUnion_u.getDir))
			 return FALSE;
		break;
	case StoreFile:
		 if (!xdr_StoreFileRequest (xdrs, &objp->FtpRequestUnion_u.storeFile))
			 return FALSE;
		break;
	case StoreAllFiles:
		 if (!xdr_StoreAllFilesRequest (xdrs, &objp->FtpRequestUnion_u.storeAllFiles))
			 return FALSE;
		break;
	case RetrieveFile:
		 if (!xdr_RetrieveFileRequest (xdrs, &objp->FtpRequestUnion_u.retrieveFile))
			 return FALSE;
		break;
	case RetrieveAllFiles:
		 if (!xdr_RetrieveAllFilesRequest (xdrs, &objp->FtpRequestUnion_u.retrieveAllFiles))
			 return FALSE;
		break;
	case DeleteFile:
		 if (!xdr_DeleteFileRequest (xdrs, &objp->FtpRequestUnion_u.deleteFile))
			 return FALSE;
		break;
	case DeleteAllFiles:
		 if (!xdr_DeleteAllFilesRequest (xdrs, &objp->FtpRequestUnion_u.deleteAllFiles))
			 return FALSE;
		break;
	case MakeWorkingEnv:
		 if (!xdr_MakeWorkingEnvRequest (xdrs, &objp->FtpRequestUnion_u.makeWorkingEnv))
			 return FALSE;
		break;
	case CleanDir:
		 if (!xdr_CleanDirRequest (xdrs, &objp->FtpRequestUnion_u.cleanDir))
			 return FALSE;
		break;
	default:
		return FALSE;
	}
	return TRUE;
}

bool_t
xdr_FtpRequest (XDR *xdrs, FtpRequest *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_FtpConnectionInfo (xdrs, &objp->connection))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->flags))
		 return FALSE;
	 if (!xdr_FtpRequestUnion (xdrs, &objp->request))
		 return FALSE;
	return TRUE;
}
